import aashram from "../assets/img/aashram.jpg";
import panchyat from "../assets/img/panchyat.jpeg";
import kotafactory from "../assets/img/kotafactory.jpg";
import mai from "../assets/img/mai.jpeg";
import test from "../assets/img/test.jpg";
import delhicrime from "../assets/img/delhicrime.jpeg";
import specialoopsr from "../assets/img/Specialoopsr.jpeg";

const Data = [
  {
    id: 1,
    image: aashram,
    title: "Aashram",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 2,
    image: panchyat,
    title: "Panchayat",
    subtitle: "Amazon Prime",
    like: 0,
    dislike: 0,
  },
  {
    id: 3,
    image:
      "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRhqFk8nITteea0sobPZkX2gKuZOxYd0m4wwnJk-AdPQX39fiO90-UesKhYtriNWihHtfg1",
    title: "Mirzapur",
    subtitle: "Amazon Prime",
    like: 0,
    dislike: 0,
  },
  {
    id: 4,
    image: kotafactory,
    title: "Kota Factory",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 5,
    image: mai,
    title: "Mai",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 6,
    image: test,
    title: "Test",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 7,
    image: delhicrime,
    title: "Delhi Crime",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 8,
    image: specialoopsr,
    title: "Special Oops",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
];

export default Data;

