// Data.jsx
const Data = [
  {
    id: 1,
    image: "/img/aashram.jpg",
    title: "Aashram",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 2,
    image: "/img/panchyat.jpeg",
    title: "Panchayat",
    subtitle: "Amazon Prime",
    like: 0,
    dislike: 0,
  },
  {
    id: 3,
    image:
      "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRhqFk8nITteea0sobPZkX2gKuZOxYd0m4wwnJk-AdPQX39fiO90-UesKhYtriNWihHtfg1",
    title: "Mirzapur",
    subtitle: "Amazon Prime",
    like: 0,
    dislike: 0,
  },
  {
    id: 4,
    image: "/img/kotafactory.jpeg",
    title: "Kota Factory",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 5,
    image: "/img/mai.jpeg",
    title: "Mai",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 6,
    image: "/img/test.jpg",
    title: "Test",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 7,
    image: "/img/delhicrime.jpeg",
    title: "Delhi Crime",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
  {
    id: 8,
    image: "/img/Specialoopsr.jpeg",
    title: "Special Oops",
    subtitle: "Netflix",
    like: 0,
    dislike: 0,
  },
];

export default Data;
